// TODO: Mock out a state object for the Reselect selectors

// Note: You'll need to refactor generateSidebarCards to make this easier to test
// The goal should be to refactor out an intermediate selector
// that produces an array of props objects, but doesn't actually pass them into
// <SidebarCard>
describe("getDashboards", () => {
  xtest("takes a state object and returns state.dashboards", () => {});
});
describe("getMetrics", () => {
  xtest("takes a state object and returns state.instance.metrics", () => {});
});
describe("generateSidebarCardProps", () => {
  //TODO: Do we need a enhance the selector to provide a better error condition here?
  xtest("returns undefined if state.dashboards is empty", () => {});
  xtest("returns a title prop equal to value.name", () => {});
  xtest("returns key and href props equal to key prepended by a /", () => {});
  xtest("returns an icon prop equal to value.summaryCard.icon", () => {});
  // etc etc etc. Use Istanbul test reported to
});

describe("generateSidebarCards", () => {
  xtest("maps over an array of props generated by generateSidebarCardProps and passes them into <SidebarCards>", () => {});
  // Any possible error checking that should happen here?
});
