const fs = require("fs");
const path = require("path");
// const axios = require("axios");

// Scrape the tag from package JSON
const version = process.env.npm_package_version;

// Scrape the latest content from from the CHANGELOG
// The regular expression matches a leading anchor tag that semantic-release prepends
// to all generated releases. This means that by grabbing the element at index one of the
// array generated by split, we should be grabbing the most recent changelog content

// This solution will potentially break if the semantic-release template changes
// View and troubleshoot the RexExp at https://regexr.com/3kof2

const changelogPath = path.resolve(__dirname, "..", "CHANGELOG.md");
const changelogContent = fs.readFileSync(changelogPath, { encoding: "ascii" });
const semverAnchorRegEx = /<a name="[0-9.]+"><\/a>\n\n## \[[0-9.]+\]\([\w://.-]+\) \(\d{4}-\d{2}-\d{2}\)\n\n/g;
const bodyOfLatestGeneratedChangeLogEntry = changelogContent.split(
  semverAnchorRegEx
)[1];

const payload = {
  tag_name: `v${version}`,
  target_commitish: "master",
  name: `v${version}`,
  body: bodyOfLatestGeneratedChangeLogEntry,
  draft: true,
  prerelease: false
};
console.log(payload);

// We need to authenticate a post request with the payload to generate releases
// axios
//   .post(
//     "https://github.com/repos/DecipherNow/gm-fabric-dashboard/releases",
//     payload
//   )
//   .then(data => console.log(data))
//   .catch(err => console.log(`ERR: ${err}`));
